apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  labels:
    app: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: collector:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: collector
spec:
  type: NodePort
  selector:
    app: collector
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000